services:
  postgres:
    image: postgres:16
    container_name: capstone
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: barterbuddy
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    external: false
